### ISSUE TITLE
在华为mate8（Android7.0）会有warning：ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.

### ISSUE THREAD

**Issue by hacjy** [lexluthors/CompressTools-Android#1]
W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
                                                                java.io.IOException: Invalid marker: 89
                                                                    at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1852)
                                                                    at android.media.ExifInterface.loadAttributes(ExifInterface.java:1485)
                                                                    at android.media.ExifInterface.<init>(ExifInterface.java:1122)
                                                                    at news.jaywei.com.compresslib.BitmapUtil.getScaledBitmap(BitmapUtil.java:172)
                                                                    at news.jaywei.com.compresslib.BitmapUtil.compressImageJni(BitmapUtil.java:217)
                                                                    at news.jaywei.com.compresslib.CompressTools$1.run(CompressTools.java:87)
                                                                    at java.lang.Thread.run(Thread.java:776)

**Comment by lexluthors** [comment]
你查看下是不是图片损坏了，看看是不是图片的问题。

**Comment by penghongru** [comment]
同样出现这个问题，红米4X，7.0
